### ISSUE TITLE
How To Build on Ubuntu 14.04

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/libslave#9]
I guessed that the idea is to download thus
(using Ubuntu 14.04 + gcc 4.8 as usual)

cd ~
git clone https://github.com/tarantool/libslave.git tarantool-libslave
cd tarantool-libslave
git submodule init
git submodule update
cmake .
make

But that fails.
Using Ubuntu 14.04 + gcc 4.8 I get this:
"
...
[ 16%] Building CXX object CMakeFiles/slave.dir/field.cpp.o
In file included from /home/pgulutzan/tarantool-libslave/field.cpp:19:0:
/home/pgulutzan/tarantool-libslave/field.h:55:15: error: ‘slave::Field::Field’ names constructor
/home/pgulutzan/tarantool-libslave/field.h:145:15: error: ‘slave::Field::Field’ names constructor
/home/pgulutzan/tarantool-libslave/field.h:152:15: error: ‘slave::Field::Field’ names constructor
make[2]: *** [CMakeFiles/slave.dir/field.cpp.o] Error 1
make[1]: *** [CMakeFiles/slave.dir/all] Error 2
make: *** [all] Error 2
" 

Using Ubuntu 17.04 and gcc 6.3 I get this:
~/tarantool-libslave/field.h:19:25: fatal error: boost/any.hpp: No such file or directory
#include <boost/any.hpp>
Compilation terminated.

I also tried the instructions at https://github.com/vozbu/libslave,
but still failed.

Perhaps this is just a problem with missing build instructions?

**Comment by ligurio** [comment]
I don't know regarding Ubuntu 14.04, but building works fine on Ubuntu 20.04. Steps are the as described in description.

**Comment by Totktonada** [comment]
Hi, Peter!

I'll close the issue, because the build works at least on Ubuntu Bionic (18.04) now (in CI). Feel free to reopen if you'll meet problems of this kind again.

**Comment by pgulutzan** [comment]
Totktonada: I tried again today with Ubuntu 18.04. It hangs after git submodule update:
Cloning into '/home/pgulutzan/tarantool-libslave/mysql'...
but I won't reopen.

**Comment by Totktonada** [comment]
It does not hang, it fetches the whole mysql sources, because someone had a thought that it is good idea to add mysql as the submodule. I hope we'll elimitate it in the scope of #23.
